spring:
  application:
    name: F1 Manager Miage Project
  datasource:
    url: jdbc:postgresql://ep-wispy-feather-59013458-pooler.eu-central-1.aws.neon.tech:5432/verceldb?sslmode=require
    username: default
    password: Dz5HFyP8lVhG
  jpa:
    ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
